server:
  port: 8004

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/product_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: product-service


  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: productCreated:com.productservice.event.producer.inventory.ProductCreatedEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1


cloudinary:
  cloud_name: dfruwhu2f
  api_key: 319338817255964
  api_secret: DsNjd_fHnxcw8-BwdeHKwfvErn4

