server:
  port: 8004

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/product_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/T-shop
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  application:
    name: product-service
eureka:
  client:
  service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1


jwt:
  auth:
    converter:
      resource-id: identity-rest-api

cloudinary:
  cloud_name: dfruwhu2f
  api_key: 319338817255964
  api_secret: DsNjd_fHnxcw8-BwdeHKwfvErn4

