spring:
  application:
    name: discovery-server

  cloud:
    config:
      enabled=false:
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: ${SERVICE_PORT}
