spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/inventory_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: inventory-service

  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: inventory-topic

    consumer:
      group-id: inventoryGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: productCreated:com.inventoryservice.event.consumer.product.ProductCreatedEvent

    admin:
      auto-create: true

server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
